### ISSUE TITLE
Text is incorrect in the backwards incompatibility rules page

### ISSUE THREAD

**Issue by rushilShetty** [znsio/archived-specmatic-documentation#23]
**The text is incorrect in the backwards incompatibility rules page for "Mandatory key becomes optional" operation.**

[Source page](https://github.com/znsio/specmatic-documentation/blob/master/documentation/backward_compatibility_rules.md#requests) 

Current:
<html>
<body>

Mandatory key becomes optional | compatible | Consumers who were not sending this key before will now be expected to send it
-- | -- | --

</body>
</html>

Expected:
<html>
<body>

Mandatory key becomes optional | compatible | Consumers who were sending this key before will now not need to send it
-- | -- | --

</body>
</html>

**Comment by harikrishnan83** [comment]
@rushilShetty thanks for reporting the issue, I have modified the content, please check.

**Comment by rushilShetty** [comment]
Thanks. I confirm it's fixed.
