### ISSUE TITLE
Qontract documentation for automatically picking up the static stubs is not clear.

### ISSUE THREAD

**Issue by anandbagmar** [znsio/archived-specmatic-documentation#3]
Apparently there is a syntax & folder structure to be followed where the stub json files should be placed. Documentation needs to be clear about this.

Also, is there a need to hardwire it in this fashion?

Hari has more context

**Comment by harikrishnan83** [comment]
Hello @anandbagmar , thanks for reporting the issue. The correct documentation is in below link.
https://qontract.run/documentation/service_virtualisation.html
