### ISSUE TITLE
additionalProperties needs to be documented

### ISSUE THREAD

**Issue by joelrosario** [znsio/archived-specmatic-documentation#47]
Specmatic supports the use of `additionalProperties` in an object schema, where the value is either an object schema or `false`. `additionalProperties` with the value `true` (free-form objects) is not supported.

For reference, here's the [OpenAPI documentation](https://swagger.io/docs/specification/data-models/dictionaries/).

**Comment by DevNwamini** [comment]
### **Using additionalProperties in Specmatic**

Specmatic provides support for using the additionalProperties keyword within an object schema to define how additional properties should be handled. It allows you to set rules for properties that are not explicitly listed in your schema. There are two valid values for additionalProperties in Specmatic:

Object Schema: You can specify another schema that additional properties should adhere to. This means that any additional properties not explicitly defined in your schema must conform to this object schema.

false: This indicates that no additional properties are allowed. Any properties not explicitly defined in your schema will result in an error.

Usage Examples
Allowing Additional Properties with Constraints
To allow additional properties while imposing constraints on them, you can define an object schema for the additional properties. Here's an example:


#yaml
properties:
name:
type: string
age:
type: integer
additionalProperties:
type: object
properties:
additionalProperty1:
type: string
additionalProperty2:
type: number


In this example, name and age are explicitly defined properties, and any additional properties must adhere to the schema specified under additionalProperties.

Disallowing Additional Properties
If you want to disallow any additional properties, you can set additionalProperties to false. Here's an example:

#yaml
properties:
name:
type: string
age:
type: integer
additionalProperties: false

In this case, only name and age are allowed properties, and any extra properties will result in an error.

Important Note
Specmatic does not support the usage of additionalProperties with the value true, which would indicate free-form objects. Please ensure that you use one of the supported options mentioned above.

Further Reference
For more details on how to work with schemas and additionalProperties in Specmatic, you can refer to the [OpenAPI documentation](https://www.openapis.org/).

**Comment by harikrishnan83** [comment]
@Youngemmy5956 thanks for your comment. We just added support for `additionalProperties: true` in release [0.81.0](https://github.com/znsio/specmatic/releases/tag/0.81.0), thanks to @jaydeepk. If you can update your content and create a PR with a section / page under [https://github.com/znsio/specmatic-documentation/tree/master/documentation](https://github.com/znsio/specmatic-documentation/tree/master/documentation), we will be happy to accept it. cc @joelrosario @jaydeepk

**Comment by harikrishnan83** [comment]
@Youngemmy5956 closing this issue since we have not heard back and also since Specmatic now fully supports OpenAPI `additionalProperties`. Please feel free to reopen the issue if you have anything to add. Thanks.
